"""Editorial content for SEO category pages and the home intro block (used by seo_build.py)."""

CATS = [
 dict(key='azure', es='examenes-practica-azure', en='azure-practice-exams',
  exams=['az-900', 'az-104', 'az-305', 'ai-901'],
  title_es='Exámenes de práctica de Azure gratis (AZ-900, AZ-104, AZ-305) | EarnYourCert',
  title_en='Free Azure Practice Exams (AZ-900, AZ-104, AZ-305) | EarnYourCert',
  h1_es='Exámenes de práctica de Azure', h1_en='Azure practice exams',
  desc_es='Simuladores de examen gratis para las certificaciones de Microsoft Azure: AZ-900, AZ-104, AZ-305 y AI-901. Preguntas tipo examen con explicaciones y simulacros cronometrados.',
  desc_en='Free practice tests for Microsoft Azure certifications: AZ-900, AZ-104, AZ-305 and AI-901. Exam-style questions with explanations and timed mock exams.',
  intro_es=['Si estás preparando una certificación de Microsoft Azure, practicar con preguntas tipo examen es la forma más rápida de detectar qué dominios dominas y cuáles no. Aquí tienes simuladores de examen gratuitos para las certificaciones de Azure más demandadas, con preguntas originales basadas en las guías oficiales de Microsoft.',
            'Cada simulacro reproduce el formato real: 50 preguntas ponderadas por dominio, tiempo limitado y un aprobado del 70%. Además de opción múltiple, encontrarás preguntas de sí/no, de completar frases y de listas desplegables, como en el examen de Microsoft.'],
  intro_en=['If you are preparing for a Microsoft Azure certification, practicing with exam-style questions is the fastest way to find out which domains you have mastered and which you haven\'t. Here you get free practice exams for the most in-demand Azure certifications, with original questions based on Microsoft\'s official study guides.',
            'Every mock exam follows the real format: 50 questions weighted by domain, a time limit and a 70% pass mark. Besides multiple choice you\'ll find yes/no, sentence-completion and drop-down questions, just like on the Microsoft exam.'],
  path_es='¿Por dónde empezar? AZ-900 (Azure Fundamentals) es la puerta de entrada y no requiere experiencia previa. Después, AZ-104 (Azure Administrator) es la certificación de administración más pedida, y AZ-305 (Azure Solutions Architect Expert) es el siguiente paso para diseñar soluciones. Si te interesa la IA, AI-901 cubre los fundamentos de IA en Azure con Microsoft Foundry.',
  path_en='Where to start? AZ-900 (Azure Fundamentals) is the entry point and requires no prior experience. Next, AZ-104 (Azure Administrator) is the most requested administration certification, and AZ-305 (Azure Solutions Architect Expert) is the next step to design solutions. If you are into AI, AI-901 covers Azure AI fundamentals with Microsoft Foundry.',
  faq_es=[('¿Cuál es el examen de Azure más fácil para empezar?', 'AZ-900 (Microsoft Azure Fundamentals). Cubre conceptos de la nube, servicios principales de Azure, seguridad, precios y gobernanza, sin necesidad de experiencia técnica previa.'),
          ('¿Necesito aprobar AZ-900 antes de AZ-104?', 'No es obligatorio, pero es recomendable: AZ-900 asienta los conceptos que AZ-104 da por sabidos.'),
          ('¿Las preguntas son las del examen real?', 'No. Son preguntas originales escritas a partir de la guía oficial de habilidades evaluadas de cada examen; no publicamos "dumps".')],
  faq_en=[('Which Azure exam is the easiest to start with?', 'AZ-900 (Microsoft Azure Fundamentals). It covers cloud concepts, core Azure services, security, pricing and governance, with no technical experience required.'),
          ('Do I need to pass AZ-900 before AZ-104?', 'It isn\'t required, but it helps: AZ-900 builds the concepts that AZ-104 assumes you already know.'),
          ('Are these the real exam questions?', 'No. They are original questions written from each exam\'s official skills-measured guide; we don\'t publish dumps.')]),
 dict(key='m365', es='examenes-practica-microsoft-365', en='microsoft-365-practice-exams',
  exams=['ab-900', 'ab-650', 'md-102', 'ms-700', 'ms-721', 'ms-102'],
  title_es='Exámenes de práctica de Microsoft 365, Copilot y Teams gratis | EarnYourCert',
  title_en='Free Microsoft 365, Copilot and Teams Practice Exams | EarnYourCert',
  h1_es='Exámenes de práctica de Microsoft 365, Copilot y Teams', h1_en='Microsoft 365, Copilot and Teams practice exams',
  desc_es='Test de práctica gratis para AB-900, AB-650, MD-102, MS-700, MS-721 y MS-102: administración de Microsoft 365, Copilot, agentes, Intune y Teams con preguntas tipo examen.',
  desc_en='Free practice tests for AB-900, AB-650, MD-102, MS-700, MS-721 and MS-102: Microsoft 365, Copilot, agents, Intune and Teams administration with exam-style questions.',
  intro_es=['Las certificaciones de Microsoft 365 validan que sabes administrar el entorno de trabajo moderno: usuarios y licencias, Exchange, SharePoint, Teams, dispositivos con Intune y, cada vez más, Microsoft 365 Copilot y los agentes de IA. Aquí puedes practicar gratis con simulacros que siguen los temarios vigentes.',
            'Mantenemos los bancos de preguntas al día con cada cambio de temario de Microsoft, incluidos los nuevos exámenes de Copilot y agentes como AB-900 y AB-650.'],
  intro_en=['Microsoft 365 certifications prove you can run the modern workplace: users and licenses, Exchange, SharePoint, Teams, devices with Intune and, increasingly, Microsoft 365 Copilot and AI agents. Practice for free with mock exams that follow the current outlines.',
            'We keep the question banks up to date with every Microsoft outline change, including the new Copilot and agent exams such as AB-900 and AB-650.'],
  path_es='¿Por dónde empezar? AB-900 (Copilot and Agent Administration Fundamentals) es la base. Para administración, AB-650 (Microsoft 365 and AI Services Administrator) es la nueva certificación asociada, MD-102 cubre los dispositivos con Intune y MS-700 la administración de Teams. MS-721 es para telefonía, salas y dispositivos de Teams. MS-102 se retira el 30 de noviembre de 2026.',
  path_en='Where to start? AB-900 (Copilot and Agent Administration Fundamentals) is the foundation. For administration, AB-650 (Microsoft 365 and AI Services Administrator) is the new associate certification, MD-102 covers devices with Intune and MS-700 covers Teams administration. MS-721 is for Teams Phone, rooms and devices. MS-102 retires on November 30, 2026.',
  faq_es=[('¿Qué sustituye a MS-102?', 'Microsoft retira MS-102 el 30 de noviembre de 2026. La nueva certificación asociada de administración de Microsoft 365 es AB-650, que también incluye Copilot y agentes.'),
          ('¿Hay un examen de práctica de Copilot?', 'Sí: AB-900 cubre los fundamentos de administración de Copilot y agentes, y AB-650 la administración avanzada de Microsoft 365 y servicios de IA.'),
          ('¿Son gratis?', 'Sí, puedes practicar gratis sin registrarte. La versión Pro elimina el límite diario de preguntas.')],
  faq_en=[('What replaces MS-102?', 'Microsoft retires MS-102 on November 30, 2026. The new associate Microsoft 365 administration certification is AB-650, which also covers Copilot and agents.'),
          ('Is there a Copilot practice exam?', 'Yes: AB-900 covers Copilot and agent administration fundamentals, and AB-650 covers advanced Microsoft 365 and AI services administration.'),
          ('Are they free?', 'Yes, you can practice for free without signing up. Pro removes the daily question limit.')]),
 dict(key='security', es='examenes-practica-seguridad-microsoft', en='microsoft-security-practice-exams',
  exams=['sc-900', 'sc-300', 'sc-200', 'sc-500'],
  title_es='Exámenes de práctica de seguridad de Microsoft (SC-900, SC-300, SC-200) | EarnYourCert',
  title_en='Microsoft Security Practice Exams (SC-900, SC-300, SC-200) | EarnYourCert',
  h1_es='Exámenes de práctica de seguridad de Microsoft', h1_en='Microsoft security practice exams',
  desc_es='Simuladores gratis para SC-900, SC-300, SC-200 y SC-500: identidad con Entra, Defender, Sentinel, Purview y seguridad de IA, con preguntas tipo examen y explicaciones.',
  desc_en='Free practice tests for SC-900, SC-300, SC-200 and SC-500: identity with Entra, Defender, Sentinel, Purview and AI security, with exam-style questions and explanations.',
  intro_es=['Las certificaciones de seguridad de Microsoft cubren identidad y acceso con Microsoft Entra, operaciones de seguridad con Defender XDR y Microsoft Sentinel, protección de datos con Purview y la seguridad de la nube y la IA. Practica con simulacros gratuitos basados en las guías oficiales.',
            'Cada pregunta incluye la explicación de por qué la respuesta es correcta, para que aprendas el concepto y no solo memorices.'],
  intro_en=['Microsoft security certifications cover identity and access with Microsoft Entra, security operations with Defender XDR and Microsoft Sentinel, data protection with Purview, and cloud and AI security. Practice with free mock exams based on the official study guides.',
            'Every question explains why the answer is correct, so you learn the concept instead of memorizing.'],
  path_es='¿Por dónde empezar? SC-900 (Security, Compliance and Identity Fundamentals) es el punto de partida. Después elige especialidad: SC-300 para identidad y acceso, SC-200 para analistas de operaciones de seguridad (SOC) y SC-500 para ingeniería de seguridad de la nube y la IA.',
  path_en='Where to start? SC-900 (Security, Compliance and Identity Fundamentals) is the starting point. Then pick a specialty: SC-300 for identity and access, SC-200 for security operations (SOC) analysts and SC-500 for cloud and AI security engineering.',
  faq_es=[('¿Qué examen de seguridad de Microsoft hago primero?', 'SC-900, que cubre los fundamentos de seguridad, cumplimiento e identidad sin requisitos previos.'),
          ('¿SC-300 o SC-200?', 'SC-300 se centra en identidad y acceso con Microsoft Entra; SC-200 en detección y respuesta con Defender XDR y Sentinel.'),
          ('¿Las preguntas se actualizan?', 'Sí, revisamos los bancos con cada cambio de temario de Microsoft.')],
  faq_en=[('Which Microsoft security exam should I take first?', 'SC-900, which covers security, compliance and identity fundamentals with no prerequisites.'),
          ('SC-300 or SC-200?', 'SC-300 focuses on identity and access with Microsoft Entra; SC-200 on detection and response with Defender XDR and Sentinel.'),
          ('Are the questions updated?', 'Yes, we review the banks with every Microsoft outline change.')]),
 dict(key='data', es='examenes-practica-datos-ia-microsoft', en='microsoft-data-ai-practice-exams',
  exams=['pl-300', 'dp-600', 'ai-901'],
  title_es='Exámenes de práctica de Power BI, Fabric e IA de Microsoft | EarnYourCert',
  title_en='Power BI, Fabric and Microsoft AI Practice Exams | EarnYourCert',
  h1_es='Exámenes de práctica de datos e IA de Microsoft', h1_en='Microsoft data and AI practice exams',
  desc_es='Test de práctica gratis para PL-300 (Power BI), DP-600 (Fabric) y AI-901 (Azure AI): preguntas tipo examen con explicaciones y simulacros cronometrados.',
  desc_en='Free practice tests for PL-300 (Power BI), DP-600 (Fabric) and AI-901 (Azure AI): exam-style questions with explanations and timed mock exams.',
  intro_es=['Si trabajas con datos o IA en el ecosistema de Microsoft, estas certificaciones validan tus conocimientos de Power BI, Microsoft Fabric y Azure AI. Practica gratis con preguntas originales que siguen los temarios oficiales.',
            'Encontrarás preguntas sobre preparación y modelado de datos, DAX, Direct Lake, KQL, Spark, IA responsable, modelos generativos y agentes.'],
  intro_en=['If you work with data or AI in the Microsoft ecosystem, these certifications validate your Power BI, Microsoft Fabric and Azure AI skills. Practice for free with original questions that follow the official outlines.',
            'You\'ll find questions on data preparation and modeling, DAX, Direct Lake, KQL, Spark, responsible AI, generative models and agents.'],
  path_es='¿Por dónde empezar? PL-300 (Power BI Data Analyst) es la certificación de análisis de datos más popular. DP-600 (Fabric Analytics Engineer) es el siguiente paso para soluciones de análisis en Microsoft Fabric. AI-901 cubre los fundamentos de IA en Azure.',
  path_en='Where to start? PL-300 (Power BI Data Analyst) is the most popular data analysis certification. DP-600 (Fabric Analytics Engineer) is the next step for analytics solutions in Microsoft Fabric. AI-901 covers Azure AI fundamentals.',
  faq_es=[('¿PL-300 o DP-600?', 'PL-300 se centra en Power BI (preparar, modelar y visualizar datos); DP-600 en soluciones de análisis completas en Microsoft Fabric.'),
          ('¿Hay preguntas de DAX?', 'Sí, PL-300 y DP-600 incluyen preguntas de DAX, modelado y rendimiento.'),
          ('¿Son gratis?', 'Sí, puedes empezar gratis sin registrarte.')],
  faq_en=[('PL-300 or DP-600?', 'PL-300 focuses on Power BI (prepare, model and visualize data); DP-600 on end-to-end analytics solutions in Microsoft Fabric.'),
          ('Are there DAX questions?', 'Yes, PL-300 and DP-600 include DAX, modeling and performance questions.'),
          ('Are they free?', 'Yes, you can start for free without signing up.')]),
]

HOME_ES = dict(
 h2='Exámenes de práctica gratis para certificaciones de Microsoft',
 paras=['EarnYourCert es un simulador de exámenes de certificación de Microsoft con preguntas tipo examen, explicaciones detalladas y repaso inteligente. Puedes practicar gratis, sin registrarte, para Azure, Microsoft 365, Copilot, Teams, seguridad, datos e IA.',
        'Cada test de práctica sigue el formato del examen oficial: preguntas ponderadas por dominio, tiempo limitado y aprobado del 70%, con preguntas de opción múltiple, sí/no, desplegables y completar frases. Todas las preguntas son originales y se basan en las guías oficiales de Microsoft.'],
 faq=[('¿Dónde puedo hacer exámenes de práctica de Microsoft gratis?', 'En EarnYourCert puedes hacer simulacros gratuitos de las principales certificaciones de Microsoft (AZ-900, AZ-104, SC-900, AB-900, MD-102, PL-300 y más) sin necesidad de registrarte.'),
      ('¿Son preguntas reales del examen?', 'No. Son preguntas originales escritas a partir de la guía oficial "Skills measured" de cada examen. No publicamos "exam dumps".'),
      ('¿Cómo funcionan los simulacros?', 'Cada simulacro tiene 50 preguntas ponderadas por dominio, como el examen real, con un aprobado del 70% y explicaciones al terminar.')])
HOME_EN = dict(
 h2='Free practice exams for Microsoft certifications',
 paras=['EarnYourCert is a Microsoft certification exam simulator with exam-style questions, detailed explanations and smart review. Practice for free, without signing up, for Azure, Microsoft 365, Copilot, Teams, security, data and AI.',
        'Every practice test follows the official exam format: questions weighted by domain, a time limit and a 70% pass mark, with multiple choice, yes/no, drop-down and sentence-completion questions. All questions are original and based on Microsoft\'s official study guides.'],
 faq=[('Where can I take free Microsoft practice exams?', 'On EarnYourCert you can take free mock exams for the main Microsoft certifications (AZ-900, AZ-104, SC-900, AB-900, MD-102, PL-300 and more) without signing up.'),
      ('Are these real exam questions?', 'No. They are original questions written from each exam\'s official "Skills measured" guide. We don\'t publish exam dumps.'),
      ('How do the mock exams work?', 'Each mock exam has 50 questions weighted by domain, like the real exam, with a 70% pass mark and explanations at the end.')])
